// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relations;

#nullable disable

namespace Relations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241208201105_changeBalanceDataType")]
    partial class changeBalanceDataType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("orderNumber")
                .StartsAt(1000L)
                .IncrementsBy(5);

            modelBuilder.Entity("Relations.MOCK_DATA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MOCK_DATAs");
                });

            modelBuilder.Entity("Relations.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ammount")
                        .HasColumnType("int");

                    b.Property<int>("orderNumber")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.ToTable("orders");
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = "10",
                            Content = "very much content",
                            Title = "title test"
                        },
                        new
                        {
                            Id = "9",
                            Content = "Content of first post",
                            Title = "First Post"
                        },
                        new
                        {
                            Id = "2",
                            Content = "Content of second post",
                            Title = "Second Post"
                        });
                });

            modelBuilder.Entity("Relations.PostTag", b =>
                {
                    b.Property<string>("tagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("postId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AddedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("tagId", "postId");

                    b.HasIndex("postId");

                    b.ToTable("PostTag");

                    b.HasData(
                        new
                        {
                            tagId = "1",
                            postId = "10",
                            AddedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            tagId = "25",
                            postId = "9",
                            AddedOn = new DateTime(2024, 12, 8, 22, 11, 4, 840, DateTimeKind.Local).AddTicks(9988)
                        },
                        new
                        {
                            tagId = "2",
                            postId = "9",
                            AddedOn = new DateTime(2024, 12, 8, 22, 11, 4, 845, DateTimeKind.Local).AddTicks(1145)
                        },
                        new
                        {
                            tagId = "25",
                            postId = "2",
                            AddedOn = new DateTime(2024, 12, 8, 22, 11, 4, 845, DateTimeKind.Local).AddTicks(1189)
                        });
                });

            modelBuilder.Entity("Relations.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = "1"
                        },
                        new
                        {
                            Id = "25"
                        },
                        new
                        {
                            Id = "2"
                        });
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.HasOne("Relations.Tag", null)
                        .WithMany("Posts")
                        .HasForeignKey("TagId");
                });

            modelBuilder.Entity("Relations.PostTag", b =>
                {
                    b.HasOne("Relations.Post", "post")
                        .WithMany("postTags")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relations.Tag", "Tag")
                        .WithMany("postTags")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("post");
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.Navigation("postTags");
                });

            modelBuilder.Entity("Relations.Tag", b =>
                {
                    b.Navigation("Posts");

                    b.Navigation("postTags");
                });
#pragma warning restore 612, 618
        }
    }
}
