// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Relations;

#nullable disable

namespace Relations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.HasSequence<int>("orderNumber")
                .StartsAt(1000L)
                .IncrementsBy(5);

            modelBuilder.Entity("Relations.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NationalityId")
                        .HasColumnType("int");

                    b.HasKey("AuthorId");

                    b.HasIndex("NationalityId");

                    b.ToTable("Authors", (string)null);

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Name = "Gabrial jesus",
                            NationalityId = 2000
                        },
                        new
                        {
                            AuthorId = 2,
                            Name = "Abdullah Ibrahim",
                            NationalityId = 3000
                        },
                        new
                        {
                            AuthorId = 3,
                            Name = "cr7",
                            NationalityId = 2000
                        },
                        new
                        {
                            AuthorId = 4,
                            Name = "Messi",
                            NationalityId = 5000
                        },
                        new
                        {
                            AuthorId = 5,
                            Name = "abo treka",
                            NationalityId = 1000
                        });
                });

            modelBuilder.Entity("Relations.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("BookId");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books", (string)null);

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            AuthorId = 2,
                            Name = "",
                            Price = 20f
                        },
                        new
                        {
                            BookId = 2,
                            AuthorId = 3,
                            Name = "head first dp",
                            Price = 20f
                        },
                        new
                        {
                            BookId = 3,
                            AuthorId = 4,
                            Name = "head first ooa&d",
                            Price = 20f
                        },
                        new
                        {
                            BookId = 4,
                            AuthorId = 5,
                            Name = "grokking algorithm",
                            Price = 20f
                        },
                        new
                        {
                            BookId = 5,
                            AuthorId = 2,
                            Name = "c# in a nutshell",
                            Price = 20f
                        },
                        new
                        {
                            BookId = 6,
                            AuthorId = 3,
                            Name = "pro c# .net development",
                            Price = 20f
                        });
                });

            modelBuilder.Entity("Relations.MOCK_DATA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Balance")
                        .HasColumnType("float");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MOCK_DATAs", (string)null);
                });

            modelBuilder.Entity("Relations.Nationality", b =>
                {
                    b.Property<int>("NationalityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NationalityId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NationalityId");

                    b.ToTable("Nationalities", (string)null);

                    b.HasData(
                        new
                        {
                            NationalityId = 1000,
                            Name = "Russian"
                        },
                        new
                        {
                            NationalityId = 2000,
                            Name = "Colombian"
                        },
                        new
                        {
                            NationalityId = 3000,
                            Name = "American"
                        },
                        new
                        {
                            NationalityId = 4000,
                            Name = "britsh"
                        },
                        new
                        {
                            NationalityId = 5000,
                            Name = "Egyptian"
                        });
                });

            modelBuilder.Entity("Relations.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ammount")
                        .HasColumnType("int");

                    b.Property<int>("orderNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValueSql("NEXT VALUE FOR orderNumber");

                    b.HasKey("OrderId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TagId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "10",
                            Content = "very much content",
                            Title = "title test"
                        },
                        new
                        {
                            Id = "9",
                            Content = "Content of first post",
                            Title = "First Post"
                        },
                        new
                        {
                            Id = "2",
                            Content = "Content of second post",
                            Title = "Second Post"
                        });
                });

            modelBuilder.Entity("Relations.PostTag", b =>
                {
                    b.Property<string>("tagId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("postId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("AddedOn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.HasKey("tagId", "postId");

                    b.HasIndex("postId");

                    b.ToTable("PostTag", (string)null);

                    b.HasData(
                        new
                        {
                            tagId = "1",
                            postId = "10",
                            AddedOn = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            tagId = "25",
                            postId = "9",
                            AddedOn = new DateTime(2024, 12, 10, 19, 35, 46, 674, DateTimeKind.Local).AddTicks(4157)
                        },
                        new
                        {
                            tagId = "2",
                            postId = "9",
                            AddedOn = new DateTime(2024, 12, 10, 19, 35, 46, 678, DateTimeKind.Local).AddTicks(6060)
                        },
                        new
                        {
                            tagId = "25",
                            postId = "2",
                            AddedOn = new DateTime(2024, 12, 10, 19, 35, 46, 678, DateTimeKind.Local).AddTicks(6102)
                        });
                });

            modelBuilder.Entity("Relations.Tag", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1"
                        },
                        new
                        {
                            Id = "25"
                        },
                        new
                        {
                            Id = "2"
                        });
                });

            modelBuilder.Entity("Relations.Author", b =>
                {
                    b.HasOne("Relations.Nationality", "nationality")
                        .WithMany("authors")
                        .HasForeignKey("NationalityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("nationality");
                });

            modelBuilder.Entity("Relations.Book", b =>
                {
                    b.HasOne("Relations.Author", "Author")
                        .WithMany("books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.HasOne("Relations.Tag", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Relations.PostTag", b =>
                {
                    b.HasOne("Relations.Post", "post")
                        .WithMany("postTags")
                        .HasForeignKey("postId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Relations.Tag", "Tag")
                        .WithMany("postTags")
                        .HasForeignKey("tagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("post");
                });

            modelBuilder.Entity("Relations.Author", b =>
                {
                    b.Navigation("books");
                });

            modelBuilder.Entity("Relations.Nationality", b =>
                {
                    b.Navigation("authors");
                });

            modelBuilder.Entity("Relations.Post", b =>
                {
                    b.Navigation("postTags");
                });

            modelBuilder.Entity("Relations.Tag", b =>
                {
                    b.Navigation("postTags");
                });
#pragma warning restore 612, 618
        }
    }
}
